import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Hammas Taiminen",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="min-h-screen font-maven bg-primary-foreground">
				{children}
			</body>
		</html>
	);
}
